name: Build and Test

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: run install, lint, build and test
        run: |
          npm install
          npm lint
          npm lint:ts
          npm run build 
          npm run test